bash -x no_text.sh "la BATAILLE"
bash -x no_text.sh "la CALAMITE"
bash -x no_text.sh "la CAVERNE"
bash -x no_text.sh "la CHASSERESSE"
bash -x no_text.sh "la CHUTE du VENT"
bash -x no_text.sh "la DECOUVERTE"
bash -x no_text.sh "la FENETRE"
bash -x no_text.sh "la FIN"
bash -x no_text.sh "la FORET"
bash -x no_text.sh "la FRONTIERE"
bash -x no_text.sh "la MER"
bash -x no_text.sh "la MOISSON"
bash -x no_text.sh "la MONTAGNE"
bash -x no_text.sh "la PENOMBRE"
bash -x no_text.sh "la RENCONTRE FORTUITE"
bash -x no_text.sh "la TRAHISON"
bash -x no_text.sh "l'AUTEUR"
bash -x no_text.sh "le BARDE"
bash -x no_text.sh "le CHATEAU"
bash -x no_text.sh "le CONSUL"
bash -x no_text.sh "le DESERT"
bash -x no_text.sh "le DIPLOMATE"
bash -x no_text.sh "le GARDE"
bash -x no_text.sh "le GARDIEN de LUMIERE"
bash -x no_text.sh "le LUNATIQUE"
bash -x no_text.sh "le MARCHAND"
bash -x no_text.sh "le MARCHE"
bash -x no_text.sh "le MARIN"
bash -x no_text.sh "le MOULIN"
bash -x no_text.sh "le PACTE"
bash -x no_text.sh "le PEINTRE"
bash -x no_text.sh "le PENITENT"
bash -x no_text.sh "le RITUEL"
bash -x no_text.sh "le SAUVAGE"
bash -x no_text.sh "le SOLDAT"
bash -x no_text.sh "le VOYAGE"
bash -x no_text.sh "l'EXCUSE"
bash -x no_text.sh "l'ILE"
bash -x no_text.sh "l'ORIGINE"
